<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="L-BG-P10405304" name="uk.co.capita.advantagecontractor.tests.LoginWithInvalidCredTest" tests="1" failures="0" timestamp="01 Dec 2017 11:49:09 GMT" time="0.606" errors="1">
  <testcase name="loginWithInvalidCredTest" time="0.606" classname="uk.co.capita.advantagecontractor.tests.LoginWithInvalidCredTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at uk.co.capita.advantagecontractor.basetest.BaseTest.takeScreenShot(BaseTest.java:269)
	at uk.co.capita.advantagecontractor.basetest.BaseTest.reportFailure(BaseTest.java:249)
	at uk.co.capita.advantagecontractor.basetest.BaseTest.initialize(BaseTest.java:96)
	at uk.co.capita.advantagecontractor.tests.LoginWithInvalidCredTest.loginWithInvalidCredTest(LoginWithInvalidCredTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- loginWithInvalidCredTest -->
</testsuite> <!-- uk.co.capita.advantagecontractor.tests.LoginWithInvalidCredTest -->
